DROP TABLE PAGO;
CREATE TABLE PAGO(   --CREANDO TABLA PAGO
    IDPAGO NUMBER(9) CONSTRAINT PAGO_PK PRIMARY KEY,
    PAGFECHA VARCHAR2(10) CONSTRAINT PAGO_NN1  NOT NULL,
    PAGMONTO NUMBER(12) CONSTRAINT PAGO_NN2 NOT NULL,
    PAGMES NUMBER(2) CONSTRAINT PAGO_NN3 NOT NULL,
    PAGANYO NUMBER(4) CONSTRAINT PAGO_NN4 NOT NULL,
    CLIENTE_RUTCLIENTE NUMBER(9) CONSTRAINT PAGO_NN5 NOT NULL
);

DROP TABLE VISITA;
CREATE TABLE VISITA (   --CREANDO TABLA VISITA
    IDVISITA NUMBER(9) CONSTRAINT VISITA_PK PRIMARY KEY,
    VISFECHA VARCHAR2(10) CONSTRAINT VISITA_NN1 NOT NULL,
    VISHORA VARCHAR2(5) ,
    VISLUGAR VARCHAR2(50) CONSTRAINT VISITA_NN2 NOT NULL,
    VISCOMENTARIO VARCHAR2(250) CONSTRAINT VISITA_NN3 NOT NULL,
    CLIENTE_RUTCLIENTE NUMBER(9) CONSTRAINT VISITA_NN4 NOT NULL
);

DROP TABLE CHEQUEO;
CREATE TABLE CHEQUEO (   --CREANDO TABLA CHEQUEO
    IDCHEQUEO NUMBER(9) CONSTRAINT CHEQUEO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(30) CONSTRAINT CHEQUEO_NN1 NOT NULL,
    DETALLE VARCHAR2(100) CONSTRAINT CHEQUEO_NN2 NOT NULL,
	ESTADO NUMBER(1) CONSTRAINT CHEQUEO_NN3 NOT NULL,
    CLIENTE_RUTCLIENTE NUMBER(9) CONSTRAINT CHEQUEO_NN4 NOT NULL
);

DROP TABLE CAPACITACION;
CREATE TABLE CAPACITACION(   --CREANDO TABLA CAPACITACION
    IDCAPACITACION NUMBER(9) CONSTRAINT CAPACITACION_PK PRIMARY KEY,
    CAPFECHA VARCHAR2(10) CONSTRAINT CAPACITACION_nn1 NOT NULL ,
    CAPHORA VARCHAR2(5),
    CAPLUGAR VARCHAR2(100) CONSTRAINT CAPACITACION_nn2 NOT NULL,
    CAPDURACION NUMBER(4),
    CLIENTE_RUTCLIENTE NUMBER(9) CONSTRAINT CAPACITACION_nn3 NOT NULL
);

DROP TABLE CLIENTE;
CREATE TABLE CLIENTE(   --CREANDO TABLA CLIENTE  perfil 1
    RUTCLIENTE NUMBER(9) CONSTRAINT CLIENTE_PK PRIMARY KEY, 
	CLITELEFONO VARCHAR2(20) CONSTRAINT CLIENTE_nn1 NOT NULL , 
	CLIAFP VARCHAR2(30), 
	CLISISTEMASALUD NUMBER(2), 
	CLIDIRECCION VARCHAR2(100)CONSTRAINT CLIENTE_nn2 NOT NULL, 
	CLICOMUNA VARCHAR2(50)CONSTRAINT CLIENTE_nn3 NOT NULL, 
	CLIEDAD NUMBER(3) CONSTRAINT CLIENTE_nn4 NOT NULL,
    USUARIO_RUNUSUARIO NUMBER(9) CONSTRAINT CLIENTE_nn5 NOT NULL
);

DROP TABLE PROFESIONAL;
CREATE TABLE PROFESIONAL(   --CREANDO TABLA PROFESIONAL perfil 2
	IDPROFESIONAL NUMBER(9) CONSTRAINT PROFESIONAL_PK PRIMARY KEY,
    PROTELEFONO VARCHAR(12),
    PROTITULO VARCHAR(50)CONSTRAINT PROFESIONAL_nn1 NOT NULL,
    PROPROYECTO VARCHAR(50),
	USUARIO_RUNUSUARIO NUMBER(9) CONSTRAINT PROFESIONAL_nn2 NOT NULL
);

DROP TABLE ADMINISTRATIVO;
CREATE TABLE ADMINISTRATIVO (   --CREANDO TABLA ADMINISTRATIVO PERFIL 3
	IDADMINISTRATIVO NUMBER(9) CONSTRAINT ADMINISTRATIVO_PK PRIMARY KEY,
    ADCORREO VARCHAR2(70),
    ADAREA VARCHAR2(20) CONSTRAINT ADMINISTRATIVO_NN1 NOT NULL,
	USUARIO_RUNUSUARIO NUMBER(9) CONSTRAINT ADMINISTRATIVO_NN2 NOT NULL
);

DROP TABLE USUARIO;
CREATE TABLE USUARIO(   --CREANDO TABLA USUARIO
    RUNUSUARIO NUMBER(9) CONSTRAINT USUARIO_PK PRIMARY KEY, 
	USNOMBRE VARCHAR2(30) CONSTRAINT USUARIO_nn1 NOT NULL, 
	USAPELLIDO VARCHAR2(50) CONSTRAINT USUARIO_nn2 NOT NULL, 
	USNACIMIENTO VARCHAR2(10),
	ACCESO_IDACCESO NUMBER(9) CONSTRAINT USUARIO_nn3 NOT NULL
);

DROP TABLE ACCESO;
CREATE TABLE ACCESO(   --CREANDO TABLA ACCESO
    IDACCESO NUMBER(9) CONSTRAINT ACCESO_PK PRIMARY KEY, 
	ACCUSERNAME VARCHAR2(30) CONSTRAINT ACCESO_nn1 NOT NULL, 
	ACCPASSWORD VARCHAR2(256) CONSTRAINT ACCESO_nn2 NOT NULL, 
	ROL_IDROL NUMBER(9) CONSTRAINT ACCESO_nn3 NOT NULL
);

DROP TABLE ROL;
CREATE TABLE ROL(   --CREANDO TABLA ROL
    IDROL NUMBER(9) CONSTRAINT ROL_PK PRIMARY KEY, 
	ROLNOMBRE VARCHAR2(30) CONSTRAINT ROL_nn1 NOT NULL
);

-- CREANDO FOREIGN KEY
ALTER TABLE CLIENTE   --LLAVE FORANEA  CLIENTE
ADD CONSTRAINT CLIENTE_USUARIO_FK
FOREIGN KEY(USUARIO_RUNUSUARIO)
REFERENCES USUARIO(RUNUSUARIO);

ALTER TABLE PROFESIONAL   --LLAVE FORANEA  PROFESIONAL 
ADD CONSTRAINT PROFESIONAL_USUARIO_FK
FOREIGN KEY(USUARIO_RUNUSUARIO)
REFERENCES USUARIO(RUNUSUARIO);

ALTER TABLE ADMINISTRATIVO   --LLAVE FORANEA  ADMINISTRATIVO
ADD CONSTRAINT ADMINISTRATIVO_USUARIO_FK
FOREIGN KEY (USUARIO_RUNUSUARIO)
REFERENCES USUARIO(RUNUSUARIO);

ALTER TABLE USUARIO   --LLAVE FORANEA  USUARIO
ADD CONSTRAINT USUARIO_ACCESO_FK
FOREIGN KEY (ACCESO_IDACCESO)
REFERENCES ACCESO(IDACCESO);

ALTER TABLE ACCESO   --LLAVE FORANEA  ACCESO
ADD CONSTRAINT ACCESO_ROL_FK
FOREIGN KEY (ROL_IDROL)
REFERENCES ROL(IDROL);




